# Site settings
title: ContentStyles
description: Scaffold styles and variables for markdown, WordPress entry content, etc.
url: https://ixkaito.github.io # the base hostname & protocol for your site
baseurl: '/contentstyles' # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
exclude:
  - frasco.config.js
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - README.md
